# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user-1@test.com",
  "name": "First and last name",
  "avatar": "avatar.jpg",
  "password": "abc123"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/ebeb0d6a-ede9-476b-bb15-4a8a2e35b9a5 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user-1@test.com",
  "password": "abc123"
}

###
